var searchData=
[
  ['tagid',['TagId',['../structnn_1_1nfc_1_1_tag_id.html',1,'nn::nfc']]],
  ['tagid',['TagId',['../structnn_1_1nfp_1_1_tag_id.html',1,'nn::nfp']]],
  ['taginfo',['TagInfo',['../structnn_1_1nfc_1_1_tag_info.html',1,'nn::nfc']]],
  ['taginfo',['TagInfo',['../structnn_1_1nfp_1_1_tag_info.html',1,'nn::nfp']]],
  ['tagprocessorbase',['TagProcessorBase',['../classnn_1_1font_1_1_tag_processor_base.html',1,'nn::font']]],
  ['targetagentversion',['TargetAgentVersion',['../structnn_1_1tm_1_1_target_agent_version.html',1,'nn::tm']]],
  ['targetconfig',['TargetConfig',['../structnn_1_1gfx_1_1_target_config.html',1,'nn::gfx']]],
  ['targethandle',['TargetHandle',['../structnn_1_1tm_1_1_target_handle.html',1,'nn::tm']]],
  ['targetipaddress',['TargetIpAddress',['../structnn_1_1tm_1_1_target_ip_address.html',1,'nn::tm']]],
  ['targetmacaddress',['TargetMacAddress',['../structnn_1_1tm_1_1_target_mac_address.html',1,'nn::tm']]],
  ['targetname',['TargetName',['../structnn_1_1tm_1_1_target_name.html',1,'nn::tm']]],
  ['targetprogramname',['TargetProgramName',['../structnn_1_1tm_1_1_target_program_name.html',1,'nn::tm']]],
  ['targetselectedarg',['TargetSelectedArg',['../structnn_1_1g3d_1_1viewer_1_1_target_selected_arg.html',1,'nn::g3d::viewer']]],
  ['targetserialnumber',['TargetSerialNumber',['../structnn_1_1tm_1_1_target_serial_number.html',1,'nn::tm']]],
  ['targetuser',['TargetUser',['../structnn_1_1tm_1_1_target_user.html',1,'nn::tm']]],
  ['targetversion',['TargetVersion',['../structnn_1_1gfx_1_1_target_version.html',1,'nn::gfx']]],
  ['tblendstate',['TBlendState',['../classnn_1_1gfx_1_1_t_blend_state.html',1,'nn::gfx']]],
  ['tblendstate_3c_20targetconfig_3a_3avariation_20_3e',['TBlendState&lt; TargetConfig::Variation &gt;',['../classnn_1_1gfx_1_1_t_blend_state.html',1,'nn::gfx']]],
  ['tbuffer',['TBuffer',['../classnn_1_1gfx_1_1_t_buffer.html',1,'nn::gfx']]],
  ['tbuffertextureview',['TBufferTextureView',['../classnn_1_1gfx_1_1_t_buffer_texture_view.html',1,'nn::gfx']]],
  ['tcolortargetview',['TColorTargetView',['../classnn_1_1gfx_1_1_t_color_target_view.html',1,'nn::gfx']]],
  ['tcommandbuffer',['TCommandBuffer',['../classnn_1_1gfx_1_1_t_command_buffer.html',1,'nn::gfx']]],
  ['tcpinfo',['TcpInfo',['../structnn_1_1socket_1_1_tcp_info.html',1,'nn::socket']]],
  ['tdepthstencilstate',['TDepthStencilState',['../classnn_1_1gfx_1_1_t_depth_stencil_state.html',1,'nn::gfx']]],
  ['tdepthstencilview',['TDepthStencilView',['../classnn_1_1gfx_1_1_t_depth_stencil_view.html',1,'nn::gfx']]],
  ['tdescriptorpool',['TDescriptorPool',['../classnn_1_1gfx_1_1_t_descriptor_pool.html',1,'nn::gfx']]],
  ['tdevice',['TDevice',['../classnn_1_1gfx_1_1_t_device.html',1,'nn::gfx']]],
  ['temporarybuffer',['TemporaryBuffer',['../classnn_1_1vfx_1_1_temporary_buffer.html',1,'nn::vfx']]],
  ['temporarybuffer',['TemporaryBuffer',['../structnn_1_1mii_1_1_temporary_buffer.html',1,'nn::mii']]],
  ['tessellationstateimpldata_3c_20apivariationgl4_20_3e',['TessellationStateImplData&lt; ApiVariationGl4 &gt;',['../structnn_1_1gfx_1_1_tessellation_state_impl_data_3_01_api_variation_gl4_01_4.html',1,'nn::gfx']]],
  ['tessellationstateinfo',['TessellationStateInfo',['../classnn_1_1gfx_1_1_tessellation_state_info.html',1,'nn::gfx']]],
  ['tessellationstateinfodata',['TessellationStateInfoData',['../structnn_1_1gfx_1_1_tessellation_state_info_data.html',1,'nn::gfx']]],
  ['texmap',['TexMap',['../classnn_1_1ui2d_1_1_tex_map.html',1,'nn::ui2d']]],
  ['texpkglib',['TexpkgLib',['../structnvn_tool_1_1texpkg_1_1_texpkg_lib.html',1,'nvnTool::texpkg']]],
  ['texsize',['TexSize',['../classnn_1_1ui2d_1_1_tex_size.html',1,'nn::ui2d']]],
  ['texsrt',['TexSrt',['../structnn_1_1g3d_1_1_tex_srt.html',1,'nn::g3d']]],
  ['textbox',['TextBox',['../classnn_1_1ui2d_1_1_text_box.html',1,'nn::ui2d']]],
  ['textinfo',['TextInfo',['../structnn_1_1ui2d_1_1_text_searcher_1_1_text_info.html',1,'nn::ui2d::TextSearcher']]],
  ['textinfoutf8',['TextInfoUtf8',['../structnn_1_1ui2d_1_1_text_searcher_1_1_text_info_utf8.html',1,'nn::ui2d::TextSearcher']]],
  ['textsearcher',['TextSearcher',['../classnn_1_1ui2d_1_1_text_searcher.html',1,'nn::ui2d']]],
  ['texture',['Texture',['../classnvn_1_1_texture.html',1,'nvn']]],
  ['texturearrayrange',['TextureArrayRange',['../classnn_1_1gfx_1_1_texture_array_range.html',1,'nn::gfx']]],
  ['texturearrayrangedata',['TextureArrayRangeData',['../structnn_1_1gfx_1_1_texture_array_range_data.html',1,'nn::gfx']]],
  ['texturebuilder',['TextureBuilder',['../classnvn_1_1_texture_builder.html',1,'nvn']]],
  ['texturecache',['TextureCache',['../classnn_1_1font_1_1_texture_cache.html',1,'nn::font']]],
  ['texturecompressor',['TextureCompressor',['../classnn_1_1gfx_1_1util_1_1_texture_compressor.html',1,'nn::gfx::util']]],
  ['texturecompressortargetinfo',['TextureCompressorTargetInfo',['../classnn_1_1gfx_1_1util_1_1_texture_compressor_target_info.html',1,'nn::gfx::util']]],
  ['texturecontainer',['TextureContainer',['../classnn_1_1ui2d_1_1_texture_container.html',1,'nn::ui2d']]],
  ['texturecopyregion',['TextureCopyRegion',['../classnn_1_1gfx_1_1_texture_copy_region.html',1,'nn::gfx']]],
  ['texturecopyregiondata',['TextureCopyRegionData',['../structnn_1_1gfx_1_1_texture_copy_region_data.html',1,'nn::gfx']]],
  ['texturedepthstencilmode',['TextureDepthStencilMode',['../structnvn_1_1_texture_depth_stencil_mode.html',1,'nvn']]],
  ['texturefileloadedarg',['TextureFileLoadedArg',['../structnn_1_1g3d_1_1viewer_1_1_texture_file_loaded_arg.html',1,'nn::g3d::viewer']]],
  ['texturefileunloadedarg',['TextureFileUnloadedArg',['../structnn_1_1g3d_1_1viewer_1_1_texture_file_unloaded_arg.html',1,'nn::g3d::viewer']]],
  ['textureflags',['TextureFlags',['../structnvn_1_1_texture_flags.html',1,'nvn']]],
  ['textureimpldata_3c_20apivariationgl4_20_3e',['TextureImplData&lt; ApiVariationGl4 &gt;',['../structnn_1_1gfx_1_1_texture_impl_data_3_01_api_variation_gl4_01_4.html',1,'nn::gfx']]],
  ['textureimpldata_3c_20apivariationnvn8_20_3e',['TextureImplData&lt; ApiVariationNvn8 &gt;',['../structnn_1_1gfx_1_1_texture_impl_data_3_01_api_variation_nvn8_01_4.html',1,'nn::gfx']]],
  ['textureinfo',['TextureInfo',['../classnn_1_1gfx_1_1_texture_info.html',1,'nn::gfx']]],
  ['textureinfo',['TextureInfo',['../classnn_1_1ui2d_1_1_texture_info.html',1,'nn::ui2d']]],
  ['textureinfodata',['TextureInfoData',['../structnn_1_1gfx_1_1_texture_info_data.html',1,'nn::gfx']]],
  ['texturemiprange',['TextureMipRange',['../classnn_1_1gfx_1_1_texture_mip_range.html',1,'nn::gfx']]],
  ['texturemiprangedata',['TextureMipRangeData',['../structnn_1_1gfx_1_1_texture_mip_range_data.html',1,'nn::gfx']]],
  ['textureobject',['TextureObject',['../classnn_1_1font_1_1_texture_object.html',1,'nn::font']]],
  ['texturepackagercore',['TexturePackagerCore',['../classnvn_tool_1_1texpkg_1_1_texture_packager_core.html',1,'nvnTool::texpkg']]],
  ['texturepool',['TexturePool',['../classnvn_1_1_texture_pool.html',1,'nvn']]],
  ['textureref',['TextureRef',['../classnn_1_1g3d_1_1_texture_ref.html',1,'nn::g3d']]],
  ['texturereflink',['TextureRefLink',['../classnn_1_1ui2d_1_1_texture_ref_link.html',1,'nn::ui2d']]],
  ['texturesampler',['TextureSampler',['../classnn_1_1vfx_1_1detail_1_1_texture_sampler.html',1,'nn::vfx::detail']]],
  ['texturesamplerslot',['TextureSamplerSlot',['../structnn_1_1vfx_1_1detail_1_1_texture_sampler_slot.html',1,'nn::vfx::detail']]],
  ['textureshader',['TextureShader',['../classnn_1_1mii_1_1_texture_shader.html',1,'nn::mii']]],
  ['textureshaderinfo',['TextureShaderInfo',['../classnn_1_1mii_1_1_texture_shader_info.html',1,'nn::mii']]],
  ['textureshaderinfodata',['TextureShaderInfoData',['../structnn_1_1mii_1_1_texture_shader_info_data.html',1,'nn::mii']]],
  ['texturesparsetilelayout',['TextureSparseTileLayout',['../structnvn_1_1_texture_sparse_tile_layout.html',1,'nvn']]],
  ['texturesubresource',['TextureSubresource',['../classnn_1_1gfx_1_1_texture_subresource.html',1,'nn::gfx']]],
  ['texturesubresourcedata',['TextureSubresourceData',['../structnn_1_1gfx_1_1_texture_subresource_data.html',1,'nn::gfx']]],
  ['texturesubresourcerange',['TextureSubresourceRange',['../classnn_1_1gfx_1_1_texture_subresource_range.html',1,'nn::gfx']]],
  ['texturesubresourcerangedata',['TextureSubresourceRangeData',['../structnn_1_1gfx_1_1_texture_subresource_range_data.html',1,'nn::gfx']]],
  ['textureswizzle',['TextureSwizzle',['../structnvn_1_1_texture_swizzle.html',1,'nvn']]],
  ['texturetarget',['TextureTarget',['../structnvn_1_1_texture_target.html',1,'nvn']]],
  ['textureuseinfo',['TextureUseInfo',['../structnn_1_1font_1_1detail_1_1_texture_use_info.html',1,'nn::font::detail']]],
  ['textureview',['TextureView',['../classnvn_1_1_texture_view.html',1,'nvn']]],
  ['textureviewimpldata_3c_20apivariationgl4_20_3e',['TextureViewImplData&lt; ApiVariationGl4 &gt;',['../structnn_1_1gfx_1_1_texture_view_impl_data_3_01_api_variation_gl4_01_4.html',1,'nn::gfx']]],
  ['textureviewimpldata_3c_20apivariationnvn8_20_3e',['TextureViewImplData&lt; ApiVariationNvn8 &gt;',['../structnn_1_1gfx_1_1_texture_view_impl_data_3_01_api_variation_nvn8_01_4.html',1,'nn::gfx']]],
  ['textureviewinfo',['TextureViewInfo',['../classnn_1_1gfx_1_1_texture_view_info.html',1,'nn::gfx']]],
  ['textureviewinfodata',['TextureViewInfoData',['../structnn_1_1gfx_1_1_texture_view_info_data.html',1,'nn::gfx']]],
  ['textwriterbase',['TextWriterBase',['../classnn_1_1font_1_1_text_writer_base.html',1,'nn::font']]],
  ['tfence',['TFence',['../classnn_1_1gfx_1_1_t_fence.html',1,'nn::gfx']]],
  ['threadlocalstorage',['ThreadLocalStorage',['../classnn_1_1os_1_1_thread_local_storage.html',1,'nn::os']]],
  ['threadtype',['ThreadType',['../structnn_1_1os_1_1_thread_type.html',1,'nn::os']]],
  ['tick',['Tick',['../classnn_1_1os_1_1_tick.html',1,'nn::os']]],
  ['tiledcacheaction',['TiledCacheAction',['../structnvn_1_1_tiled_cache_action.html',1,'nvn']]],
  ['timemodule',['TimeModule',['../classnn_1_1spy_1_1_time_module.html',1,'nn::spy']]],
  ['timeoutcanceller',['TimeoutCanceller',['../classnn_1_1atk_1_1viewer_1_1_timeout_canceller.html',1,'nn::atk::viewer']]],
  ['timerange',['TimeRange',['../structnn_1_1atk_1_1_time_range.html',1,'nn::atk']]],
  ['timerevent',['TimerEvent',['../classnn_1_1os_1_1_timer_event.html',1,'nn::os']]],
  ['timereventtype',['TimerEventType',['../structnn_1_1os_1_1_timer_event_type.html',1,'nn::os']]],
  ['timespan',['TimeSpan',['../classnn_1_1_time_span.html',1,'nn']]],
  ['timespantype',['TimeSpanType',['../structnn_1_1_time_span_type.html',1,'nn']]],
  ['timestampbufferimpldata_3c_20apivariationgl4_20_3e',['TimestampBufferImplData&lt; ApiVariationGl4 &gt;',['../structnn_1_1gfx_1_1_timestamp_buffer_impl_data_3_01_api_variation_gl4_01_4.html',1,'nn::gfx']]],
  ['timestampbufferimpldata_3c_20apivariationnvn8_20_3e',['TimestampBufferImplData&lt; ApiVariationNvn8 &gt;',['../structnn_1_1gfx_1_1_timestamp_buffer_impl_data_3_01_api_variation_nvn8_01_4.html',1,'nn::gfx']]],
  ['timeval',['TimeVal',['../structnn_1_1socket_1_1_time_val.html',1,'nn::socket']]],
  ['timezone',['TimeZone',['../structnn_1_1time_1_1_time_zone.html',1,'nn::time']]],
  ['timezonerule',['TimeZoneRule',['../structnn_1_1time_1_1_time_zone_rule.html',1,'nn::time']]],
  ['tinteroperation_3c_20apivariation_3c_20apitypenvn_20_3e_20_3e',['TInteroperation&lt; ApiVariation&lt; ApiTypeNvn &gt; &gt;',['../classnn_1_1gfx_1_1_t_interoperation_3_01_api_variation_3_01_api_type_nvn_01_4_01_4.html',1,'nn::gfx']]],
  ['tinteroperation_3c_20apivariationgl4_20_3e',['TInteroperation&lt; ApiVariationGl4 &gt;',['../classnn_1_1gfx_1_1_t_interoperation_3_01_api_variation_gl4_01_4.html',1,'nn::gfx']]],
  ['tinymt',['TinyMt',['../classnn_1_1util_1_1_tiny_mt.html',1,'nn::util']]],
  ['tlsslot',['TlsSlot',['../structnn_1_1os_1_1_tls_slot.html',1,'nn::os']]],
  ['tmemorypool',['TMemoryPool',['../classnn_1_1gfx_1_1_t_memory_pool.html',1,'nn::gfx']]],
  ['toolconnector',['ToolConnector',['../classnn_1_1vfx_1_1viewer_1_1detail_1_1_tool_connector.html',1,'nn::vfx::viewer::detail']]],
  ['toolconnector',['ToolConnector',['../classnn_1_1ui2d_1_1viewer_1_1_tool_connector.html',1,'nn::ui2d::viewer']]],
  ['toolconnectoractual',['ToolConnectorActual',['../classnn_1_1vfx_1_1viewer_1_1detail_1_1_tool_connector_actual.html',1,'nn::vfx::viewer::detail']]],
  ['touchattribute',['TouchAttribute',['../structnn_1_1hid_1_1_touch_attribute.html',1,'nn::hid']]],
  ['touchdragbutton',['TouchDragButton',['../classnn_1_1ui2d_1_1_touch_drag_button.html',1,'nn::ui2d']]],
  ['touchoffbutton',['TouchOffButton',['../classnn_1_1ui2d_1_1_touch_off_button.html',1,'nn::ui2d']]],
  ['touchoffcheckbutton',['TouchOffCheckButton',['../classnn_1_1ui2d_1_1_touch_off_check_button.html',1,'nn::ui2d']]],
  ['touchscreenstate',['TouchScreenState',['../structnn_1_1hid_1_1_touch_screen_state.html',1,'nn::hid']]],
  ['touchstate',['TouchState',['../structnn_1_1hid_1_1_touch_state.html',1,'nn::hid']]],
  ['tpipeline',['TPipeline',['../classnn_1_1gfx_1_1_t_pipeline.html',1,'nn::gfx']]],
  ['tpipeline_3c_20targetconfig_3a_3avariation_20_3e',['TPipeline&lt; TargetConfig::Variation &gt;',['../classnn_1_1gfx_1_1_t_pipeline.html',1,'nn::gfx']]],
  ['tquerybuffer',['TQueryBuffer',['../classnn_1_1gfx_1_1_t_query_buffer.html',1,'nn::gfx']]],
  ['tqueue',['TQueue',['../classnn_1_1gfx_1_1_t_queue.html',1,'nn::gfx']]],
  ['transientbufferallocator',['TransientBufferAllocator',['../classnn_1_1gfx_1_1util_1_1_transient_buffer_allocator.html',1,'nn::gfx::util']]],
  ['transientbufferallocatorholder',['TransientBufferAllocatorHolder',['../classnn_1_1gfx_1_1util_1_1_transient_buffer_allocator_holder.html',1,'nn::gfx::util']]],
  ['transientdescriptorallocator',['TransientDescriptorAllocator',['../classnn_1_1gfx_1_1util_1_1_transient_descriptor_allocator.html',1,'nn::gfx::util']]],
  ['transientdescriptorallocatorholder',['TransientDescriptorAllocatorHolder',['../classnn_1_1gfx_1_1util_1_1_transient_descriptor_allocator_holder.html',1,'nn::gfx::util']]],
  ['transientmemorypoolallocator',['TransientMemoryPoolAllocator',['../classnn_1_1gfx_1_1util_1_1_transient_memory_pool_allocator.html',1,'nn::gfx::util']]],
  ['transientmemorypoolallocatorholder',['TransientMemoryPoolAllocatorHolder',['../classnn_1_1gfx_1_1util_1_1_transient_memory_pool_allocator_holder.html',1,'nn::gfx::util']]],
  ['transparentadjuster',['TransparentAdjuster',['../classnn_1_1mii_1_1_transparent_adjuster.html',1,'nn::mii']]],
  ['transparentadjustergpubuffer',['TransparentAdjusterGpuBuffer',['../classnn_1_1mii_1_1_transparent_adjuster_gpu_buffer.html',1,'nn::mii']]],
  ['transparentadjusterinfo',['TransparentAdjusterInfo',['../classnn_1_1mii_1_1_transparent_adjuster_info.html',1,'nn::mii']]],
  ['transparentadjusterinfodata',['TransparentAdjusterInfoData',['../structnn_1_1mii_1_1_transparent_adjuster_info_data.html',1,'nn::mii']]],
  ['trasterizerstate',['TRasterizerState',['../classnn_1_1gfx_1_1_t_rasterizer_state.html',1,'nn::gfx']]],
  ['trootsignature',['TRootSignature',['../classnn_1_1gfx_1_1_t_root_signature.html',1,'nn::gfx']]],
  ['trootsignature_3c_20targetconfig_3a_3avariation_20_3e',['TRootSignature&lt; TargetConfig::Variation &gt;',['../classnn_1_1gfx_1_1_t_root_signature.html',1,'nn::gfx']]],
  ['tsampler',['TSampler',['../classnn_1_1gfx_1_1_t_sampler.html',1,'nn::gfx']]],
  ['tsemaphore',['TSemaphore',['../classnn_1_1gfx_1_1_t_semaphore.html',1,'nn::gfx']]],
  ['tshader',['TShader',['../classnn_1_1gfx_1_1_t_shader.html',1,'nn::gfx']]],
  ['tswapchain',['TSwapChain',['../classnn_1_1gfx_1_1_t_swap_chain.html',1,'nn::gfx']]],
  ['ttessellationstate',['TTessellationState',['../classnn_1_1gfx_1_1_t_tessellation_state.html',1,'nn::gfx']]],
  ['ttexture',['TTexture',['../classnn_1_1gfx_1_1_t_texture.html',1,'nn::gfx']]],
  ['ttextureview',['TTextureView',['../classnn_1_1gfx_1_1_t_texture_view.html',1,'nn::gfx']]],
  ['ttimestampbuffer',['TTimestampBuffer',['../classnn_1_1gfx_1_1_t_timestamp_buffer.html',1,'nn::gfx']]],
  ['tvertexstate',['TVertexState',['../classnn_1_1gfx_1_1_t_vertex_state.html',1,'nn::gfx']]],
  ['tvertexstate_3c_20targetconfig_3a_3avariation_20_3e',['TVertexState&lt; TargetConfig::Variation &gt;',['../classnn_1_1gfx_1_1_t_vertex_state.html',1,'nn::gfx']]],
  ['tviewportscissorstate',['TViewportScissorState',['../classnn_1_1gfx_1_1_t_viewport_scissor_state.html',1,'nn::gfx']]],
  ['tviewportscissorstate_3c_20targetconfig_3a_3avariation_20_3e',['TViewportScissorState&lt; TargetConfig::Variation &gt;',['../classnn_1_1gfx_1_1_t_viewport_scissor_state.html',1,'nn::gfx']]],
  ['type64',['Type64',['../unionnn_1_1font_1_1detail_1_1_type64.html',1,'nn::font::detail']]],
  ['typedstorage',['TypedStorage',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20char_2c_201024u_20_2a16u_2c_208u_20_3e',['TypedStorage&lt; char, 1024u *16u, 8u &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20char_2c_20208_2c_208u_20_3e',['TypedStorage&lt; char, 208, 8u &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20detail_3a_3akeycodecomposerstorage_2c_2032_2c_208_20_3e',['TypedStorage&lt; detail::KeyCodeComposerStorage, 32, 8 &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20detail_3a_3akeycodemapstorage_2c_204_20_2a1024_2c_208_20_3e',['TypedStorage&lt; detail::KeyCodeMapStorage, 4 *1024, 8 &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20detail_3a_3amultiwaitholderimpl_2c_20nn_5fos_5fdetail_5fcalc_5fobject_5fsize_280_2c_207_29_2c_20nn_5falignof_28void_20_2a_29_3e',['TypedStorage&lt; detail::MultiWaitHolderImpl, NN_OS_DETAIL_CALC_OBJECT_SIZE(0, 7), NN_ALIGNOF(void *)&gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20detail_3a_3amultiwaitobjectlist_2c_20nn_5fos_5fdetail_5fcalc_5fobject_5fsize_280_2c_202_29_2c_20nn_5falignof_28void_20_2a_29_3e',['TypedStorage&lt; detail::MultiWaitObjectList, NN_OS_DETAIL_CALC_OBJECT_SIZE(0, 2), NN_ALIGNOF(void *)&gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20errorviewerstartupparamforapplicationerror_2c_20datasize_2c_204_20_3e',['TypedStorage&lt; ErrorViewerStartupParamForApplicationError, DataSize, 4 &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20nn_3a_3atimespan_2c_20sizeof_28nn_3a_3atimespan_29_2c_20nn_5falignof_28nn_3a_3atimespan_29_3e',['TypedStorage&lt; nn::TimeSpan, sizeof(nn::TimeSpan), NN_ALIGNOF(nn::TimeSpan)&gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20util_3a_3aintrusivelistnode_2c_20nn_5fos_5fdetail_5fcalc_5fobject_5fsize_280_2c_202_29_2c_20nn_5falignof_28void_20_2a_29_3e',['TypedStorage&lt; util::IntrusiveListNode, NN_OS_DETAIL_CALC_OBJECT_SIZE(0, 2), NN_ALIGNOF(void *)&gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20vibrationfileparsercontextimpl_2c_2080_2c_20nn_5falignof_28void_20_2a_29_3e',['TypedStorage&lt; VibrationFileParserContextImpl, 80, NN_ALIGNOF(void *)&gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]],
  ['typedstorage_3c_20void_20_2a_2c_2064_2c_208_20_3e',['TypedStorage&lt; void *, 64, 8 &gt;',['../structnn_1_1util_1_1_typed_storage.html',1,'nn::util']]]
];
