var searchData=
[
  ['aabb',['Aabb',['../structnn_1_1g3d_1_1_aabb.html',1,'nn::g3d']]],
  ['aacdecoder',['AacDecoder',['../classnn_1_1codec_1_1_aac_decoder.html',1,'nn::codec']]],
  ['aacdecodertype',['AacDecoderType',['../structnn_1_1codec_1_1_aac_decoder_type.html',1,'nn::codec']]],
  ['abortinfo',['AbortInfo',['../structnn_1_1diag_1_1_abort_info.html',1,'nn::diag']]],
  ['abortobserverholder',['AbortObserverHolder',['../structnn_1_1diag_1_1_abort_observer_holder.html',1,'nn::diag']]],
  ['accessorbase',['AccessorBase',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resanimconstantdata_20_3e',['AccessorBase&lt; ResAnimConstantData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resanimcurvedata_20_3e',['AccessorBase&lt; ResAnimCurveData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resattrvardata_20_3e',['AccessorBase&lt; ResAttrVarData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resboneanimdata_20_3e',['AccessorBase&lt; ResBoneAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resbonedata_20_3e',['AccessorBase&lt; ResBoneData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resbonevisibilityanimdata_20_3e',['AccessorBase&lt; ResBoneVisibilityAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20rescameraanimdata_20_3e',['AccessorBase&lt; ResCameraAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resdicdata_20_3e',['AccessorBase&lt; ResDicData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resexternalfiledata_20_3e',['AccessorBase&lt; ResExternalFileData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resfiledata_20_3e',['AccessorBase&lt; ResFileData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resfoganimdata_20_3e',['AccessorBase&lt; ResFogAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20reskeyshapedata_20_3e',['AccessorBase&lt; ResKeyShapeData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20reslightanimdata_20_3e',['AccessorBase&lt; ResLightAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resmaterialanimdata_20_3e',['AccessorBase&lt; ResMaterialAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resmaterialdata_20_3e',['AccessorBase&lt; ResMaterialData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resmeshdata_20_3e',['AccessorBase&lt; ResMeshData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resmodeldata_20_3e',['AccessorBase&lt; ResModelData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20respermaterialanimdata_20_3e',['AccessorBase&lt; ResPerMaterialAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resrenderinfodata_20_3e',['AccessorBase&lt; ResRenderInfoData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20ressamplervardata_20_3e',['AccessorBase&lt; ResSamplerVarData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20ressceneanimdata_20_3e',['AccessorBase&lt; ResSceneAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderarchivedata_20_3e',['AccessorBase&lt; ResShaderArchiveData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderassigndata_20_3e',['AccessorBase&lt; ResShaderAssignData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshadercontainerdata_20_3e',['AccessorBase&lt; ResShaderContainerData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderfiledata_20_3e',['AccessorBase&lt; ResShaderFileData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderoptiondata_20_3e',['AccessorBase&lt; ResShaderOptionData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderparamdata_20_3e',['AccessorBase&lt; ResShaderParamData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderprogramdata_20_3e',['AccessorBase&lt; ResShaderProgramData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshaderstorageblockvardata_20_3e',['AccessorBase&lt; ResShaderStorageBlockVarData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshadervariationdata_20_3e',['AccessorBase&lt; ResShaderVariationData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshadingmodeldata_20_3e',['AccessorBase&lt; ResShadingModelData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshapeanimdata_20_3e',['AccessorBase&lt; ResShapeAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resshapedata_20_3e',['AccessorBase&lt; ResShapeData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resskeletalanimdata_20_3e',['AccessorBase&lt; ResSkeletalAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resskeletondata_20_3e',['AccessorBase&lt; ResSkeletonData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20ressubmeshdata_20_3e',['AccessorBase&lt; ResSubMeshData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20restexturedata_20_3e',['AccessorBase&lt; ResTextureData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20restexturefiledata_20_3e',['AccessorBase&lt; ResTextureFileData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resuniformblockvardata_20_3e',['AccessorBase&lt; ResUniformBlockVarData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resuniformvardata_20_3e',['AccessorBase&lt; ResUniformVarData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resuserdatadata_20_3e',['AccessorBase&lt; ResUserDataData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resvertexattrdata_20_3e',['AccessorBase&lt; ResVertexAttrData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resvertexdata_20_3e',['AccessorBase&lt; ResVertexData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['accessorbase_3c_20resvertexshapeanimdata_20_3e',['AccessorBase&lt; ResVertexShapeAnimData &gt;',['../classnn_1_1util_1_1_accessor_base.html',1,'nn::util']]],
  ['actionqueue',['ActionQueue',['../classnn_1_1ui2d_1_1_button_base_1_1_action_queue.html',1,'nn::ui2d::ButtonBase']]],
  ['addonsoundarchive',['AddonSoundArchive',['../classnn_1_1atk_1_1_addon_sound_archive.html',1,'nn::atk']]],
  ['addrinfo',['AddrInfo',['../structnn_1_1socket_1_1_addr_info.html',1,'nn::socket']]],
  ['adjustablenetworksystemclock',['AdjustableNetworkSystemClock',['../classnn_1_1time_1_1_adjustable_network_system_clock.html',1,'nn::time']]],
  ['adjustableusersystemclock',['AdjustableUserSystemClock',['../classnn_1_1time_1_1_adjustable_user_system_clock.html',1,'nn::time']]],
  ['adpcmcontext',['AdpcmContext',['../structnn_1_1codec_1_1_adpcm_context.html',1,'nn::codec']]],
  ['adpcmcontext',['AdpcmContext',['../structnn_1_1audio_1_1_adpcm_context.html',1,'nn::audio']]],
  ['adpcmheaderinfo',['AdpcmHeaderInfo',['../structnn_1_1audio_1_1_adpcm_header_info.html',1,'nn::audio']]],
  ['adpcmparameter',['AdpcmParameter',['../structnn_1_1codec_1_1_adpcm_parameter.html',1,'nn::codec']]],
  ['adpcmparameter',['AdpcmParameter',['../structnn_1_1audio_1_1_adpcm_parameter.html',1,'nn::audio']]],
  ['advancedwavesoundinfo',['AdvancedWaveSoundInfo',['../structnn_1_1atk_1_1_sound_archive_1_1_advanced_wave_sound_info.html',1,'nn::atk::SoundArchive']]],
  ['aes128cbcdecryptor',['Aes128CbcDecryptor',['../classnn_1_1crypto_1_1_aes128_cbc_decryptor.html',1,'nn::crypto']]],
  ['aes128cbcencryptor',['Aes128CbcEncryptor',['../classnn_1_1crypto_1_1_aes128_cbc_encryptor.html',1,'nn::crypto']]],
  ['aes128ccmdecryptor',['Aes128CcmDecryptor',['../classnn_1_1crypto_1_1_aes128_ccm_decryptor.html',1,'nn::crypto']]],
  ['aes128ccmencryptor',['Aes128CcmEncryptor',['../classnn_1_1crypto_1_1_aes128_ccm_encryptor.html',1,'nn::crypto']]],
  ['aes128cmacgenerator',['Aes128CmacGenerator',['../classnn_1_1crypto_1_1_aes128_cmac_generator.html',1,'nn::crypto']]],
  ['aes128ctrdecryptor',['Aes128CtrDecryptor',['../classnn_1_1crypto_1_1_aes128_ctr_decryptor.html',1,'nn::crypto']]],
  ['aes128ctrencryptor',['Aes128CtrEncryptor',['../classnn_1_1crypto_1_1_aes128_ctr_encryptor.html',1,'nn::crypto']]],
  ['aes128gcmdecryptor',['Aes128GcmDecryptor',['../classnn_1_1crypto_1_1_aes128_gcm_decryptor.html',1,'nn::crypto']]],
  ['aes128gcmencryptor',['Aes128GcmEncryptor',['../classnn_1_1crypto_1_1_aes128_gcm_encryptor.html',1,'nn::crypto']]],
  ['aesdecryptor',['AesDecryptor',['../classnn_1_1crypto_1_1_aes_decryptor.html',1,'nn::crypto']]],
  ['aesdecryptor_3c_2016_20_3e',['AesDecryptor&lt; 16 &gt;',['../classnn_1_1crypto_1_1_aes_decryptor.html',1,'nn::crypto']]],
  ['aesencryptor',['AesEncryptor',['../classnn_1_1crypto_1_1_aes_encryptor.html',1,'nn::crypto']]],
  ['aesencryptor_3c_2016_20_3e',['AesEncryptor&lt; 16 &gt;',['../classnn_1_1crypto_1_1_aes_encryptor.html',1,'nn::crypto']]],
  ['alignment',['Alignment',['../classnn_1_1ui2d_1_1_alignment.html',1,'nn::ui2d']]],
  ['allocatorhash',['AllocatorHash',['../structnn_1_1mem_1_1_standard_allocator_1_1_allocator_hash.html',1,'nn::mem::StandardAllocator']]],
  ['allpaneanimator',['AllPaneAnimator',['../classnn_1_1ui2d_1_1viewer_1_1_all_pane_animator.html',1,'nn::ui2d::viewer']]],
  ['alphafunc',['AlphaFunc',['../structnvn_1_1_alpha_func.html',1,'nvn']]],
  ['amiibosettingsstartparam',['AmiiboSettingsStartParam',['../structnn_1_1nfp_1_1_amiibo_settings_start_param.html',1,'nn::nfp']]],
  ['analogstickstate',['AnalogStickState',['../structnn_1_1hid_1_1_analog_stick_state.html',1,'nn::hid']]],
  ['animationcounter',['AnimationCounter',['../struct_animation_counter.html',1,'']]],
  ['animator',['Animator',['../classnn_1_1ui2d_1_1_animator.html',1,'nn::ui2d']]],
  ['animbindtable',['AnimBindTable',['../classnn_1_1g3d_1_1_anim_bind_table.html',1,'nn::g3d']]],
  ['animbutton',['AnimButton',['../classnn_1_1ui2d_1_1_anim_button.html',1,'nn::ui2d']]],
  ['animcontext',['AnimContext',['../classnn_1_1g3d_1_1_anim_context.html',1,'nn::g3d']]],
  ['animframecache',['AnimFrameCache',['../structnn_1_1g3d_1_1_anim_frame_cache.html',1,'nn::g3d']]],
  ['animframectrl',['AnimFrameCtrl',['../classnn_1_1g3d_1_1_anim_frame_ctrl.html',1,'nn::g3d']]],
  ['animobj',['AnimObj',['../classnn_1_1g3d_1_1_anim_obj.html',1,'nn::g3d']]],
  ['animresource',['AnimResource',['../classnn_1_1ui2d_1_1_anim_resource.html',1,'nn::ui2d']]],
  ['animtransform',['AnimTransform',['../classnn_1_1ui2d_1_1_anim_transform.html',1,'nn::ui2d']]],
  ['animtransformbasic',['AnimTransformBasic',['../classnn_1_1ui2d_1_1_anim_transform_basic.html',1,'nn::ui2d']]],
  ['apitype',['ApiType',['../structnn_1_1gfx_1_1_api_type.html',1,'nn::gfx']]],
  ['apitypeconfig',['ApiTypeConfig',['../structnn_1_1gfx_1_1_api_type_config.html',1,'nn::gfx']]],
  ['apivariation',['ApiVariation',['../structnn_1_1gfx_1_1_api_variation.html',1,'nn::gfx']]],
  ['apiversion',['ApiVersion',['../structnn_1_1gfx_1_1_api_version.html',1,'nn::gfx']]],
  ['applicationareacreateinfo',['ApplicationAreaCreateInfo',['../structnn_1_1nfp_1_1_application_area_create_info.html',1,'nn::nfp']]],
  ['applicationerrorarg',['ApplicationErrorArg',['../classnn_1_1err_1_1_application_error_arg.html',1,'nn::err']]],
  ['applicationid',['ApplicationId',['../structnn_1_1_application_id.html',1,'nn']]],
  ['applicationinfo',['ApplicationInfo',['../structnn_1_1friends_1_1_application_info.html',1,'nn::friends']]],
  ['applicationplaystatistics',['ApplicationPlayStatistics',['../structnn_1_1pdm_1_1_application_play_statistics.html',1,'nn::pdm']]],
  ['applysceneanimrequestedarg',['ApplySceneAnimRequestedArg',['../structnn_1_1g3d_1_1viewer_1_1_apply_scene_anim_requested_arg.html',1,'nn::g3d::viewer']]],
  ['arcentry',['ArcEntry',['../classnn_1_1ui2d_1_1_arc_entry.html',1,'nn::ui2d']]],
  ['arcextractor',['ArcExtractor',['../classnn_1_1ui2d_1_1_arc_extractor.html',1,'nn::ui2d']]],
  ['arcfileinfo',['ArcFileInfo',['../classnn_1_1ui2d_1_1_arc_file_info.html',1,'nn::ui2d']]],
  ['archiveblockheader',['ArchiveBlockHeader',['../structnn_1_1ui2d_1_1_arc_extractor_1_1_archive_block_header.html',1,'nn::ui2d::ArcExtractor']]],
  ['archivefilewriter',['ArchiveFileWriter',['../classnvn_tool_1_1texpkg_1_1_archive_file_writer.html',1,'nvnTool::texpkg']]],
  ['archivehandle',['ArchiveHandle',['../classnn_1_1ui2d_1_1_archive_handle.html',1,'nn::ui2d']]],
  ['archiveheader',['ArchiveHeader',['../structnvn_tool_1_1texpkg_1_1_archive_header.html',1,'nvnTool::texpkg']]],
  ['arcresourceaccessor',['ArcResourceAccessor',['../classnn_1_1ui2d_1_1_arc_resource_accessor.html',1,'nn::ui2d']]],
  ['arcresourcelink',['ArcResourceLink',['../classnn_1_1ui2d_1_1_arc_resource_link.html',1,'nn::ui2d']]],
  ['arealoopsystem',['AreaLoopSystem',['../classnn_1_1vfx_1_1detail_1_1_area_loop_system.html',1,'nn::vfx::detail']]],
  ['arm',['Arm',['../structnn_1_1irsensor_1_1_arm.html',1,'nn::irsensor']]],
  ['assertioninfo',['AssertionInfo',['../structnn_1_1diag_1_1_assertion_info.html',1,'nn::diag']]],
  ['asynccontext',['AsyncContext',['../classnn_1_1friends_1_1_async_context.html',1,'nn::friends']]],
  ['asynccontext',['AsyncContext',['../classnn_1_1account_1_1_async_context.html',1,'nn::account']]],
  ['atkprofilereader',['AtkProfileReader',['../classnn_1_1atk_1_1_atk_profile_reader.html',1,'nn::atk']]],
  ['atkspymodule',['AtkSpyModule',['../classnn_1_1spy_1_1atk_1_1_atk_spy_module.html',1,'nn::spy::atk']]],
  ['attribute',['Attribute',['../classnn_1_1vfx_1_1detail_1_1_attribute.html',1,'nn::vfx::detail']]],
  ['attributestate',['AttributeState',['../structnn_1_1gfx_1_1_vertex_state_impl_data_3_01_api_variation_gl4_01_4_1_1_attribute_state.html',1,'nn::gfx::VertexStateImplData&lt; ApiVariationGl4 &gt;']]],
  ['audiodevicename',['AudioDeviceName',['../structnn_1_1audio_1_1_audio_device_name.html',1,'nn::audio']]],
  ['audioin',['AudioIn',['../structnn_1_1audio_1_1_audio_in.html',1,'nn::audio']]],
  ['audioinbuffer',['AudioInBuffer',['../structnn_1_1audio_1_1_audio_in_buffer.html',1,'nn::audio']]],
  ['audioininfo',['AudioInInfo',['../structnn_1_1audio_1_1_audio_in_info.html',1,'nn::audio']]],
  ['audioinparameter',['AudioInParameter',['../structnn_1_1audio_1_1_audio_in_parameter.html',1,'nn::audio']]],
  ['audioout',['AudioOut',['../structnn_1_1audio_1_1_audio_out.html',1,'nn::audio']]],
  ['audiooutbuffer',['AudioOutBuffer',['../structnn_1_1audio_1_1_audio_out_buffer.html',1,'nn::audio']]],
  ['audiooutinfo',['AudioOutInfo',['../structnn_1_1audio_1_1_audio_out_info.html',1,'nn::audio']]],
  ['audiooutparameter',['AudioOutParameter',['../structnn_1_1audio_1_1_audio_out_parameter.html',1,'nn::audio']]],
  ['audiorendererconfig',['AudioRendererConfig',['../structnn_1_1audio_1_1_audio_renderer_config.html',1,'nn::audio']]],
  ['audiorendererhandle',['AudioRendererHandle',['../structnn_1_1audio_1_1_audio_renderer_handle.html',1,'nn::audio']]],
  ['audiorendererparameter',['AudioRendererParameter',['../structnn_1_1audio_1_1_audio_renderer_parameter.html',1,'nn::audio']]],
  ['audiospymodule',['AudioSpyModule',['../classnn_1_1spy_1_1audio_1_1_audio_spy_module.html',1,'nn::spy::audio']]],
  ['authenticationsetting',['AuthenticationSetting',['../structnn_1_1nifm_1_1_authentication_setting.html',1,'nn::nifm']]],
  ['automeasure',['AutoMeasure',['../classnn_1_1perf_1_1_auto_measure.html',1,'nn::perf']]],
  ['automeasureindex',['AutoMeasureIndex',['../classnn_1_1perf_1_1_auto_measure_index.html',1,'nn::perf']]],
  ['auxi3dl2reverbtype',['AuxI3dl2ReverbType',['../structnn_1_1audio_1_1_aux_i3dl2_reverb_type.html',1,'nn::audio']]],
  ['auxreverbtype',['AuxReverbType',['../structnn_1_1audio_1_1_aux_reverb_type.html',1,'nn::audio']]],
  ['auxtype',['AuxType',['../structnn_1_1audio_1_1_aux_type.html',1,'nn::audio']]],
  ['axestomtx',['AxesToMtx',['../classnn_1_1g3d_1_1_axes_to_mtx.html',1,'nn::g3d']]],
  ['axestoquat',['AxesToQuat',['../classnn_1_1g3d_1_1_axes_to_quat.html',1,'nn::g3d']]]
];
