var searchData=
[
  ['nvn_20programming_20guide',['NVN Programming Guide',['../nvn_index.html',1,'PageGraphicsForNX']]],
  ['nvn_20texture_20packager',['NVN Texture Packager',['../nvn_texpkg_index.html',1,'PageGraphicsForNX']]],
  ['nninitstartup_28_29_20から利用可能な_20api_20リスト',['nninitStartup() から利用可能な API リスト',['../_page_notification_init_available_api_list_in_startup.html',1,'PageNotificationInit']]],
  ['npad_20の複数の機能を切り替えて実行',['Npad の複数の機能を切り替えて実行',['../_page_sample_hid_npad_integrate.html',1,'PageSampleHid']]],
  ['npadを使ったボタン入力の取得',['Npadを使ったボタン入力の取得',['../_page_sample_hid_npad_simple.html',1,'PageSampleHid']]],
  ['npadを使った_20sixaxissensor_20の状態の取得',['Npadを使った SixAxisSensor の状態の取得',['../_page_sample_hid_npad_six_axis_sensor.html',1,'PageSampleHid']]],
  ['nninitstartup',['nninitStartup',['../_page_sample_init_startup.html',1,'PageSampleInit']]],
  ['nninitstartupwithmalloc',['nninitStartupWithMalloc',['../_page_sample_init_startup_with_malloc.html',1,'PageSampleInit']]],
  ['nfc_20ライブラリによる_20mifare_20タグアクセス機能のサンプル',['NFC ライブラリによる MIFARE タグアクセス機能のサンプル',['../_page_sample_mifare_simple.html',1,'PageSampleNfc']]],
  ['nfc',['NFC',['../_page_sample_nfc.html',1,'PageSample']]],
  ['nfc_20ライブラリによる_20nfc_20タグへのパススルーアクセス機能のサンプル',['NFC ライブラリによる NFC タグへのパススルーアクセス機能のサンプル',['../_page_sample_nfc_pass_through_simple.html',1,'PageSampleNfc']]],
  ['nfp',['NFP',['../_page_sample_nfp.html',1,'PageSample']]],
  ['nfp_20ライブラリのサンプル_28複数_20nfc_20デバイスへの同時アクセス対応版_29',['NFP ライブラリのサンプル(複数 NFC デバイスへの同時アクセス対応版)',['../_page_sample_nfp_multi.html',1,'PageSampleNfp']]],
  ['nfp_20ライブラリのサンプル',['NFP ライブラリのサンプル',['../_page_sample_nfp_simple.html',1,'PageSampleNfp']]],
  ['ngc',['Ngc',['../_page_sample_ngc.html',1,'PageSample']]],
  ['ngcライブラリの基本操作',['NGCライブラリの基本操作',['../_page_sample_ngc_simple.html',1,'PageSampleNgc']]],
  ['nifm',['Nifm',['../_page_sample_nifm.html',1,'PageSample']]],
  ['nns_3a_3agfx',['nns::gfx',['../_page_sample_nns_gfx.html',1,'PageSample']]],
  ['nvn',['NVN',['../_page_sample_nvn.html',1,'PageSample']]],
  ['nvn_20tutorial_2001_3a_20getting_20started_20with_20nvn',['NVN Tutorial 01: Getting Started With NVN',['../_page_sample_nvn_tutorial01.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2002_3a_20gpu_20offline_20build_20tools',['NVN Tutorial 02: GPU Offline Build Tools',['../_page_sample_nvn_tutorial02.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2003_3a_20asset_20file_20loading',['NVN Tutorial 03: Asset File Loading',['../_page_sample_nvn_tutorial03.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2004_3a_20multithreaded_20asset_20file_20loading_2c_20cube_20maps_2c_20and_20mipmaps',['NVN Tutorial 04: Multithreaded Asset File Loading, Cube Maps, and Mipmaps',['../_page_sample_nvn_tutorial04.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2005_3a_20setting_20up_20render_20state_20and_20rendering_20debug_20text',['NVN Tutorial 05: Setting Up Render State And Rendering Debug Text',['../_page_sample_nvn_tutorial05.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2006_3a_20uniform_20block_20memory_20management',['NVN Tutorial 06: Uniform Block Memory Management',['../_page_sample_nvn_tutorial06.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2007_3a_20multithreaded_20renderer',['NVN Tutorial 07: Multithreaded Renderer',['../_page_sample_nvn_tutorial07.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2008_3a_20gpu_20statistics',['NVN Tutorial 08: GPU Statistics',['../_page_sample_nvn_tutorial08.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2009_3a_20shader_20specialization',['NVN Tutorial 09: Shader Specialization',['../_page_sample_nvn_tutorial09.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2010_3a_20nvn_20and_20opengl_20interoperation',['NVN Tutorial 10: NVN and OpenGL Interoperation',['../_page_sample_nvn_tutorial10.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_2011_3a_20runtime_20texture_20compression',['NVN Tutorial 11: Runtime Texture Compression',['../_page_sample_nvn_tutorial11.html',1,'PageSampleNvn']]],
  ['nvn_20tutorial_20library',['NVN Tutorial Library',['../_page_sample_nvn_tutorial_library.html',1,'PageSampleNvn']]],
  ['nintendo_20nx_20cpu_20profiler_20sample',['Nintendo NX CPU Profiler Sample',['../_page_sample_profiler_simple.html',1,'PageSampleProfiler']]]
];
